# Generated by Django 4.1.7 on 2023-03-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act_data',
            options={'verbose_name': 'Акуальная дата', 'verbose_name_plural': 'Акуальная дата'},
        ),
    ]
