# Generated by Django 4.1.7 on 2023-03-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_act_data_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act_data',
            name='data',
        ),
        migrations.AddField(
            model_name='act_data',
            name='current_data',
            field=models.CharField(default=2, max_length=45, verbose_name='current_data'),
            preserve_default=False,
        ),
    ]
